### ISSUE TITLE
Long message handling times get SQS stuck

### ISSUE THREAD

**Issue by bernardd** [hippware/dawdle#54]
If the time taken to synchronously handle messages retrieved from SQS exceeds the queue's visibility timeout, then the action to delete the message from the queue will still return 200 success, but the same messages will be retrieved on the next loop. If the time taken is consistently higher than the timeout, this results in the queue process getting completely stuck.

**Comment by toland** [comment]
I looked at the code today, and the problem is technically straight-forward to fix, but there are conceptual trade-offs that need to be considered.

There are three issues that are in contention: 1) SQS call efficiency (cost reduction), 2) message ordering, and 3) not letting things get stuck because of one expensive message.

If you look at [this line](https://github.com/hippware/dawdle/blob/1691bf6966437ece2f0da7c7f47bd96a8bff6ad3/lib/dawdle/client.ex#L110), Dawdle processes the messages from a batch in one process and [deletes all of the messages](https://github.com/hippware/dawdle/blob/1691bf6966437ece2f0da7c7f47bd96a8bff6ad3/lib/dawdle/client.ex#L243) when they have all finished processing. We wait until all messages have finished processing so that we can issue one delete request for the batch. 

The simplest solution appears to be handling each message in its own process and deleting it when the handler completes. This would negate the possibility of a queue clog, but it also would increase the number of SQS calls (cost) and messages would be handled out of order. The cost increase would probably be very small, and ordering isn't a big issue for us. I am interested in feedback on this approach.

**Comment by toland** [comment]
It turns out that another big issue is that we are using a FIFO queue for messages. This pretty much guarantees that an event that takes a long time to process will clog the queue unless we set the visibility timeout very high. After discussing the issue with Bernard, we decided to give up on strict ordering in order to get better throughput, and to avoid problems with clogs.
